services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.3-alpine
    ports:
      - "8123:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse-server-config:/etc/clickhouse-server/
      - ./volumes/clickhouse/database:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host=localhost", "--port=9000", "--user=default", "--password=password", "--query=SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  clickhouse-backup:
    image: altinity/clickhouse-backup:2.6.15
    environment:
      - WATCH_INTERVAL=5m
      - FULL_INTERVAL=10m
      - REMOTE_STORAGE=s3
      - BACKUPS_TO_KEEP_LOCAL=0
      - BACKUPS_TO_KEEP_REMOTE=2
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USERNAME=backup_user
      - CLICKHOUSE_PASSWORD=backup_password
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=clickhouse-backup
      - S3_FORCE_PATH_STYLE=true
      - S3_DISABLE_SSL=true
      - S3_DISABLE_CERT_VERIFICATION=true
      - S3_ACCESS_KEY=root-service-account
      - S3_SECRET_KEY=root-service-account-secret
    volumes:
      - ./volumes/clickhouse/database:/var/lib/clickhouse
    command: watch
    depends_on:
      clickhouse:
        condition: service_healthy

  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-29T22-14-52Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: TVDkAFWNueUy6u
    command: server -console-address ":9001" /data
    volumes:
      - ./volumes/minio/data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
